import { useState } from 'react';
import { Copy, Check, BarChart2, Trash2, Calendar } from 'lucide-react';
import { ApiClient } from '../services/api';

export default function LinkCard({ link, onOpenAnalytics, onDeleteClick }) {
  const [copied, setCopied] = useState(false);
  const [clicks, setClicks] = useState(link.clicks);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(link.shortUrl);
      setCopied(true);
      
      // Simulate real traffic on short url copy/visit in sandbox
      await ApiClient.recordMockClick(link.id);
      setClicks(prev => prev + 1);
      
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Clipboard copy operation failed:', err);
    }
  };

  // Determine expiration status
  const isExpired = link.expiresAt ? new Date(link.expiresAt) < new Date() : false;

  return (
    <div className="bg-white border border-[#EAEAEA] rounded-lg p-6 hover:shadow-md transition-all duration-300 flex flex-col justify-between group">
      <div>
        
        {/* Badges & Status */}
        <div className="flex items-center justify-between mb-3.5">
          <span className="text-[10px] font-bold text-[#666666] tracking-wider uppercase">
            {link.alias ? `shrt.x/${link.alias}` : 'Autogenerated'}
          </span>
          
          <div className="flex items-center space-x-1.5">
            {link.expiresAt && (
              <span className={`px-2 py-0.5 rounded-full text-[9px] font-semibold tracking-wide uppercase ${
                isExpired ? 'bg-red-50 text-red-600 border border-red-100' : 'bg-orange-50 text-orange-600 border border-orange-100'
              }`}>
                {isExpired ? 'Expired' : 'Expires Soon'}
              </span>
            )}
            <span className="inline-flex items-center rounded-full bg-blue-50 border border-blue-100 px-2 py-0.5 text-[9px] font-bold text-[#0057FF] uppercase tracking-wide">
              {clicks.toLocaleString()} Clicks
            </span>
          </div>
        </div>

        {/* Destination & Title */}
        <h4 className="text-[15px] font-bold text-[#111111] line-clamp-1 mb-1 hover:text-[#0057FF] cursor-pointer" title={link.title}>
          {link.title}
        </h4>
        
        <p className="text-[11px] text-[#666666] truncate pr-4" title={link.longUrl}>
          {link.longUrl}
        </p>

        {/* Highlighted short url */}
        <div className="mt-3.5 flex items-center space-x-1.5">
          <a
            href={link.shortUrl}
            target="_blank"
            rel="noopener noreferrer"
            onClick={async () => {
              // Sandbox interactive tracking
              await ApiClient.recordMockClick(link.id);
              setClicks(prev => prev + 1);
            }}
            className="text-[13px] font-bold text-[#0057FF] hover:underline"
          >
            {link.shortUrl}
          </a>
        </div>

        {/* Creation stamp & metadata */}
        <div className="mt-4 flex items-center space-x-3.5 text-[10px] text-gray-400 font-semibold border-t border-dashed border-gray-100 pt-3.5">
          <span className="flex items-center">
            <Calendar className="mr-1 h-3.5 w-3.5 shrink-0" />
            {new Date(link.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
          </span>
          {link.expiresAt && (
            <span className="flex items-center text-orange-400">
              <Calendar className="mr-1 h-3.5 w-3.5 shrink-0" />
              Exp: {new Date(link.expiresAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
            </span>
          )}
        </div>

      </div>

      {/* Action Footer */}
      <div className="mt-6 flex items-center justify-between border-t border-[#EAEAEA] pt-4">
        <div className="flex space-x-2">
          
          {/* Copy Action button with icon swaps */}
          <button
            onClick={handleCopy}
            className={`flex items-center space-x-1.5 px-3 py-1.5 rounded-md text-[11px] font-bold uppercase tracking-wider transition-all duration-200 focus:outline-none ${
              copied 
                ? 'bg-green-50 border border-green-200 text-green-700' 
                : 'bg-white border border-[#EAEAEA] text-gray-500 hover:text-[#111111] hover:border-gray-300'
            }`}
          >
            {copied ? (
              <>
                <Check className="h-3.5 w-3.5 stroke-[2.5]" />
                <span>Copied</span>
              </>
            ) : (
              <>
                <Copy className="h-3.5 w-3.5 stroke-[2]" />
                <span>Copy</span>
              </>
            )}
          </button>

          {/* View Insights drawer button */}
          <button
            onClick={() => onOpenAnalytics(link)}
            className="flex items-center space-x-1.5 px-3 py-1.5 rounded-md bg-white border border-[#EAEAEA] text-gray-500 hover:text-[#111111] hover:border-gray-300 text-[11px] font-bold uppercase tracking-wider transition-colors duration-200 focus:outline-none"
          >
            <BarChart2 className="h-3.5 w-3.5 stroke-[2]" />
            <span>Insights</span>
          </button>

        </div>

        {/* Delete trash button */}
        <button
          onClick={() => onDeleteClick(link)}
          aria-label="Delete Link"
          className="rounded-md p-1.5 text-gray-400 hover:bg-red-50 hover:text-red-600 transition-colors focus:outline-none"
        >
          <Trash2 className="h-4 w-4" />
        </button>

      </div>
    </div>
  );
}
